import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { QueryErrorHandler, QueryProvider } from "@/providers/QueryProvider";
import { ToastProvider } from "@/providers/ToastProvider";

export const metadata: Metadata = {
	title: "Effective Yomimono",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className="antialiased">
				<QueryProvider>
					<ToastProvider>
						<QueryErrorHandler />
						<Header />
						<div className="pt-16">{children}</div>
					</ToastProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
