/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookmarkListResponse,
  BulkBookmarksRequest,
  ErrorResponse,
  FavoriteBookmarksResponse,
  MessageResponse,
  RecentBookmarksResponse,
  SuccessResponse
} from './schemas';

/**
 * @summary 未読ブックマーク一覧
 */
export type getApiBookmarksResponse200 = {
  data: BookmarkListResponse
  status: 200
}

export type getApiBookmarksResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksResponseSuccess = (getApiBookmarksResponse200) & {
  headers: Headers;
};
export type getApiBookmarksResponseError = (getApiBookmarksResponse500) & {
  headers: Headers;
};

export type getApiBookmarksResponse = (getApiBookmarksResponseSuccess | getApiBookmarksResponseError)

export const getGetApiBookmarksUrl = () => {


  

  return `/api/bookmarks`
}

export const getApiBookmarks = async ( options?: RequestInit): Promise<getApiBookmarksResponse> => {
  
  const res = await fetch(getGetApiBookmarksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksResponse
}





export const getGetApiBookmarksQueryKey = () => {
    return [
    `/api/bookmarks`
    ] as const;
    }

    
export const getGetApiBookmarksQueryOptions = <TData = Awaited<ReturnType<typeof getApiBookmarks>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBookmarksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBookmarks>>> = ({ signal }) => getApiBookmarks({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBookmarksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBookmarks>>>
export type GetApiBookmarksQueryError = ErrorResponse


export function useGetApiBookmarks<TData = Awaited<ReturnType<typeof getApiBookmarks>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarks<TData = Awaited<ReturnType<typeof getApiBookmarks>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarks>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarks<TData = Awaited<ReturnType<typeof getApiBookmarks>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 未読ブックマーク一覧
 */

export function useGetApiBookmarks<TData = Awaited<ReturnType<typeof getApiBookmarks>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBookmarksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary ブックマーク一括登録
 */
export type postApiBookmarksBulkResponse200 = {
  data: MessageResponse
  status: 200
}

export type postApiBookmarksBulkResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiBookmarksBulkResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type postApiBookmarksBulkResponseSuccess = (postApiBookmarksBulkResponse200) & {
  headers: Headers;
};
export type postApiBookmarksBulkResponseError = (postApiBookmarksBulkResponse400 | postApiBookmarksBulkResponse500) & {
  headers: Headers;
};

export type postApiBookmarksBulkResponse = (postApiBookmarksBulkResponseSuccess | postApiBookmarksBulkResponseError)

export const getPostApiBookmarksBulkUrl = () => {


  

  return `/api/bookmarks/bulk`
}

export const postApiBookmarksBulk = async (bulkBookmarksRequest: BulkBookmarksRequest, options?: RequestInit): Promise<postApiBookmarksBulkResponse> => {
  
  const res = await fetch(getPostApiBookmarksBulkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkBookmarksRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiBookmarksBulkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiBookmarksBulkResponse
}




export const getPostApiBookmarksBulkMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksBulk>>, TError,{data: BulkBookmarksRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksBulk>>, TError,{data: BulkBookmarksRequest}, TContext> => {

const mutationKey = ['postApiBookmarksBulk'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBookmarksBulk>>, {data: BulkBookmarksRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiBookmarksBulk(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiBookmarksBulkMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBookmarksBulk>>>
    export type PostApiBookmarksBulkMutationBody = BulkBookmarksRequest
    export type PostApiBookmarksBulkMutationError = ErrorResponse

    /**
 * @summary ブックマーク一括登録
 */
export const usePostApiBookmarksBulk = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksBulk>>, TError,{data: BulkBookmarksRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBookmarksBulk>>,
        TError,
        {data: BulkBookmarksRequest},
        TContext
      > => {
      return useMutation(getPostApiBookmarksBulkMutationOptions(options), queryClient);
    }
    
/**
 * @summary お気に入り一覧
 */
export type getApiBookmarksFavoritesResponse200 = {
  data: FavoriteBookmarksResponse
  status: 200
}

export type getApiBookmarksFavoritesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksFavoritesResponseSuccess = (getApiBookmarksFavoritesResponse200) & {
  headers: Headers;
};
export type getApiBookmarksFavoritesResponseError = (getApiBookmarksFavoritesResponse500) & {
  headers: Headers;
};

export type getApiBookmarksFavoritesResponse = (getApiBookmarksFavoritesResponseSuccess | getApiBookmarksFavoritesResponseError)

export const getGetApiBookmarksFavoritesUrl = () => {


  

  return `/api/bookmarks/favorites`
}

export const getApiBookmarksFavorites = async ( options?: RequestInit): Promise<getApiBookmarksFavoritesResponse> => {
  
  const res = await fetch(getGetApiBookmarksFavoritesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksFavoritesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksFavoritesResponse
}





export const getGetApiBookmarksFavoritesQueryKey = () => {
    return [
    `/api/bookmarks/favorites`
    ] as const;
    }

    
export const getGetApiBookmarksFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBookmarksFavoritesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBookmarksFavorites>>> = ({ signal }) => getApiBookmarksFavorites({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBookmarksFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBookmarksFavorites>>>
export type GetApiBookmarksFavoritesQueryError = ErrorResponse


export function useGetApiBookmarksFavorites<TData = Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksFavorites>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarksFavorites<TData = Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksFavorites>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksFavorites>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarksFavorites<TData = Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary お気に入り一覧
 */

export function useGetApiBookmarksFavorites<TData = Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksFavorites>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBookmarksFavoritesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary 最近既読にしたブックマーク
 */
export type getApiBookmarksRecentResponse200 = {
  data: RecentBookmarksResponse
  status: 200
}

export type getApiBookmarksRecentResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksRecentResponseSuccess = (getApiBookmarksRecentResponse200) & {
  headers: Headers;
};
export type getApiBookmarksRecentResponseError = (getApiBookmarksRecentResponse500) & {
  headers: Headers;
};

export type getApiBookmarksRecentResponse = (getApiBookmarksRecentResponseSuccess | getApiBookmarksRecentResponseError)

export const getGetApiBookmarksRecentUrl = () => {


  

  return `/api/bookmarks/recent`
}

export const getApiBookmarksRecent = async ( options?: RequestInit): Promise<getApiBookmarksRecentResponse> => {
  
  const res = await fetch(getGetApiBookmarksRecentUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksRecentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksRecentResponse
}





export const getGetApiBookmarksRecentQueryKey = () => {
    return [
    `/api/bookmarks/recent`
    ] as const;
    }

    
export const getGetApiBookmarksRecentQueryOptions = <TData = Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBookmarksRecentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBookmarksRecent>>> = ({ signal }) => getApiBookmarksRecent({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBookmarksRecentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBookmarksRecent>>>
export type GetApiBookmarksRecentQueryError = ErrorResponse


export function useGetApiBookmarksRecent<TData = Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksRecent>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksRecent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarksRecent<TData = Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBookmarksRecent>>,
          TError,
          Awaited<ReturnType<typeof getApiBookmarksRecent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBookmarksRecent<TData = Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 最近既読にしたブックマーク
 */

export function useGetApiBookmarksRecent<TData = Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBookmarksRecent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBookmarksRecentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary お気に入り削除
 */
export type deleteApiBookmarksIdFavoriteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteApiBookmarksIdFavoriteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteApiBookmarksIdFavoriteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteApiBookmarksIdFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deleteApiBookmarksIdFavoriteResponseSuccess = (deleteApiBookmarksIdFavoriteResponse200) & {
  headers: Headers;
};
export type deleteApiBookmarksIdFavoriteResponseError = (deleteApiBookmarksIdFavoriteResponse400 | deleteApiBookmarksIdFavoriteResponse404 | deleteApiBookmarksIdFavoriteResponse500) & {
  headers: Headers;
};

export type deleteApiBookmarksIdFavoriteResponse = (deleteApiBookmarksIdFavoriteResponseSuccess | deleteApiBookmarksIdFavoriteResponseError)

export const getDeleteApiBookmarksIdFavoriteUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/favorite`
}

export const deleteApiBookmarksIdFavorite = async (id: number, options?: RequestInit): Promise<deleteApiBookmarksIdFavoriteResponse> => {
  
  const res = await fetch(getDeleteApiBookmarksIdFavoriteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiBookmarksIdFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiBookmarksIdFavoriteResponse
}




export const getDeleteApiBookmarksIdFavoriteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiBookmarksIdFavorite'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiBookmarksIdFavorite(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiBookmarksIdFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>>
    
    export type DeleteApiBookmarksIdFavoriteMutationError = ErrorResponse

    /**
 * @summary お気に入り削除
 */
export const useDeleteApiBookmarksIdFavorite = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiBookmarksIdFavorite>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiBookmarksIdFavoriteMutationOptions(options), queryClient);
    }
    
/**
 * @summary お気に入り追加
 */
export type postApiBookmarksIdFavoriteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type postApiBookmarksIdFavoriteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiBookmarksIdFavoriteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postApiBookmarksIdFavoriteResponse409 = {
  data: ErrorResponse
  status: 409
}

export type postApiBookmarksIdFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type postApiBookmarksIdFavoriteResponseSuccess = (postApiBookmarksIdFavoriteResponse200) & {
  headers: Headers;
};
export type postApiBookmarksIdFavoriteResponseError = (postApiBookmarksIdFavoriteResponse400 | postApiBookmarksIdFavoriteResponse404 | postApiBookmarksIdFavoriteResponse409 | postApiBookmarksIdFavoriteResponse500) & {
  headers: Headers;
};

export type postApiBookmarksIdFavoriteResponse = (postApiBookmarksIdFavoriteResponseSuccess | postApiBookmarksIdFavoriteResponseError)

export const getPostApiBookmarksIdFavoriteUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/favorite`
}

export const postApiBookmarksIdFavorite = async (id: number, options?: RequestInit): Promise<postApiBookmarksIdFavoriteResponse> => {
  
  const res = await fetch(getPostApiBookmarksIdFavoriteUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiBookmarksIdFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiBookmarksIdFavoriteResponse
}




export const getPostApiBookmarksIdFavoriteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>, TError,{id: number}, TContext> => {

const mutationKey = ['postApiBookmarksIdFavorite'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postApiBookmarksIdFavorite(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiBookmarksIdFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>>
    
    export type PostApiBookmarksIdFavoriteMutationError = ErrorResponse

    /**
 * @summary お気に入り追加
 */
export const usePostApiBookmarksIdFavorite = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBookmarksIdFavorite>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostApiBookmarksIdFavoriteMutationOptions(options), queryClient);
    }
    
/**
 * @summary ブックマークを既読にする
 */
export type patchApiBookmarksIdReadResponse200 = {
  data: SuccessResponse
  status: 200
}

export type patchApiBookmarksIdReadResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchApiBookmarksIdReadResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchApiBookmarksIdReadResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type patchApiBookmarksIdReadResponseSuccess = (patchApiBookmarksIdReadResponse200) & {
  headers: Headers;
};
export type patchApiBookmarksIdReadResponseError = (patchApiBookmarksIdReadResponse400 | patchApiBookmarksIdReadResponse404 | patchApiBookmarksIdReadResponse500) & {
  headers: Headers;
};

export type patchApiBookmarksIdReadResponse = (patchApiBookmarksIdReadResponseSuccess | patchApiBookmarksIdReadResponseError)

export const getPatchApiBookmarksIdReadUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/read`
}

export const patchApiBookmarksIdRead = async (id: number, options?: RequestInit): Promise<patchApiBookmarksIdReadResponse> => {
  
  const res = await fetch(getPatchApiBookmarksIdReadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiBookmarksIdReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiBookmarksIdReadResponse
}




export const getPatchApiBookmarksIdReadMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdRead>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdRead>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchApiBookmarksIdRead'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiBookmarksIdRead>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchApiBookmarksIdRead(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiBookmarksIdReadMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiBookmarksIdRead>>>
    
    export type PatchApiBookmarksIdReadMutationError = ErrorResponse

    /**
 * @summary ブックマークを既読にする
 */
export const usePatchApiBookmarksIdRead = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdRead>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiBookmarksIdRead>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPatchApiBookmarksIdReadMutationOptions(options), queryClient);
    }
    
/**
 * @summary ブックマークを未読に戻す
 */
export type patchApiBookmarksIdUnreadResponse200 = {
  data: SuccessResponse
  status: 200
}

export type patchApiBookmarksIdUnreadResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchApiBookmarksIdUnreadResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchApiBookmarksIdUnreadResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type patchApiBookmarksIdUnreadResponseSuccess = (patchApiBookmarksIdUnreadResponse200) & {
  headers: Headers;
};
export type patchApiBookmarksIdUnreadResponseError = (patchApiBookmarksIdUnreadResponse400 | patchApiBookmarksIdUnreadResponse404 | patchApiBookmarksIdUnreadResponse500) & {
  headers: Headers;
};

export type patchApiBookmarksIdUnreadResponse = (patchApiBookmarksIdUnreadResponseSuccess | patchApiBookmarksIdUnreadResponseError)

export const getPatchApiBookmarksIdUnreadUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/unread`
}

export const patchApiBookmarksIdUnread = async (id: number, options?: RequestInit): Promise<patchApiBookmarksIdUnreadResponse> => {
  
  const res = await fetch(getPatchApiBookmarksIdUnreadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiBookmarksIdUnreadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiBookmarksIdUnreadResponse
}




export const getPatchApiBookmarksIdUnreadMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchApiBookmarksIdUnread'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchApiBookmarksIdUnread(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiBookmarksIdUnreadMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>>
    
    export type PatchApiBookmarksIdUnreadMutationError = ErrorResponse

    /**
 * @summary ブックマークを未読に戻す
 */
export const usePatchApiBookmarksIdUnread = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiBookmarksIdUnread>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPatchApiBookmarksIdUnreadMutationOptions(options), queryClient);
    }
