/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */
import type {
  AssignLabelRequest,
  AssignLabelResponse,
  BookmarkListResponse,
  BulkBookmarksRequest,
  CreateLabelRequest,
  ErrorResponse,
  FavoriteBookmarksResponse,
  GetApiBookmarksParams,
  LabelCleanupResponse,
  LabelResponse,
  LabelsResponse,
  MessageResponse,
  RecentBookmarksResponse,
  SuccessResponse,
  UpdateLabelRequest
} from './schemas';

/**
 * @summary 未読ブックマーク一覧
 */
export type getApiBookmarksResponse200 = {
  data: BookmarkListResponse
  status: 200
}

export type getApiBookmarksResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksResponseSuccess = (getApiBookmarksResponse200) & {
  headers: Headers;
};
export type getApiBookmarksResponseError = (getApiBookmarksResponse500) & {
  headers: Headers;
};

export type getApiBookmarksResponse = (getApiBookmarksResponseSuccess | getApiBookmarksResponseError)

export const getGetApiBookmarksUrl = (params?: GetApiBookmarksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/bookmarks?${stringifiedParams}` : `/api/bookmarks`
}

export const getApiBookmarks = async (params?: GetApiBookmarksParams, options?: RequestInit): Promise<getApiBookmarksResponse> => {
  
  const res = await fetch(getGetApiBookmarksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksResponse
}



/**
 * @summary ブックマーク一括登録
 */
export type postApiBookmarksBulkResponse200 = {
  data: MessageResponse
  status: 200
}

export type postApiBookmarksBulkResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiBookmarksBulkResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type postApiBookmarksBulkResponseSuccess = (postApiBookmarksBulkResponse200) & {
  headers: Headers;
};
export type postApiBookmarksBulkResponseError = (postApiBookmarksBulkResponse400 | postApiBookmarksBulkResponse500) & {
  headers: Headers;
};

export type postApiBookmarksBulkResponse = (postApiBookmarksBulkResponseSuccess | postApiBookmarksBulkResponseError)

export const getPostApiBookmarksBulkUrl = () => {


  

  return `/api/bookmarks/bulk`
}

export const postApiBookmarksBulk = async (bulkBookmarksRequest: BulkBookmarksRequest, options?: RequestInit): Promise<postApiBookmarksBulkResponse> => {
  
  const res = await fetch(getPostApiBookmarksBulkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkBookmarksRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiBookmarksBulkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiBookmarksBulkResponse
}



/**
 * @summary お気に入り一覧
 */
export type getApiBookmarksFavoritesResponse200 = {
  data: FavoriteBookmarksResponse
  status: 200
}

export type getApiBookmarksFavoritesResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksFavoritesResponseSuccess = (getApiBookmarksFavoritesResponse200) & {
  headers: Headers;
};
export type getApiBookmarksFavoritesResponseError = (getApiBookmarksFavoritesResponse500) & {
  headers: Headers;
};

export type getApiBookmarksFavoritesResponse = (getApiBookmarksFavoritesResponseSuccess | getApiBookmarksFavoritesResponseError)

export const getGetApiBookmarksFavoritesUrl = () => {


  

  return `/api/bookmarks/favorites`
}

export const getApiBookmarksFavorites = async ( options?: RequestInit): Promise<getApiBookmarksFavoritesResponse> => {
  
  const res = await fetch(getGetApiBookmarksFavoritesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksFavoritesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksFavoritesResponse
}



/**
 * @summary 最近既読にしたブックマーク
 */
export type getApiBookmarksRecentResponse200 = {
  data: RecentBookmarksResponse
  status: 200
}

export type getApiBookmarksRecentResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiBookmarksRecentResponseSuccess = (getApiBookmarksRecentResponse200) & {
  headers: Headers;
};
export type getApiBookmarksRecentResponseError = (getApiBookmarksRecentResponse500) & {
  headers: Headers;
};

export type getApiBookmarksRecentResponse = (getApiBookmarksRecentResponseSuccess | getApiBookmarksRecentResponseError)

export const getGetApiBookmarksRecentUrl = () => {


  

  return `/api/bookmarks/recent`
}

export const getApiBookmarksRecent = async ( options?: RequestInit): Promise<getApiBookmarksRecentResponse> => {
  
  const res = await fetch(getGetApiBookmarksRecentUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiBookmarksRecentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiBookmarksRecentResponse
}



/**
 * @summary お気に入り削除
 */
export type deleteApiBookmarksIdFavoriteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type deleteApiBookmarksIdFavoriteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteApiBookmarksIdFavoriteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteApiBookmarksIdFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deleteApiBookmarksIdFavoriteResponseSuccess = (deleteApiBookmarksIdFavoriteResponse200) & {
  headers: Headers;
};
export type deleteApiBookmarksIdFavoriteResponseError = (deleteApiBookmarksIdFavoriteResponse400 | deleteApiBookmarksIdFavoriteResponse404 | deleteApiBookmarksIdFavoriteResponse500) & {
  headers: Headers;
};

export type deleteApiBookmarksIdFavoriteResponse = (deleteApiBookmarksIdFavoriteResponseSuccess | deleteApiBookmarksIdFavoriteResponseError)

export const getDeleteApiBookmarksIdFavoriteUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/favorite`
}

export const deleteApiBookmarksIdFavorite = async (id: number, options?: RequestInit): Promise<deleteApiBookmarksIdFavoriteResponse> => {
  
  const res = await fetch(getDeleteApiBookmarksIdFavoriteUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiBookmarksIdFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiBookmarksIdFavoriteResponse
}



/**
 * @summary お気に入り追加
 */
export type postApiBookmarksIdFavoriteResponse200 = {
  data: SuccessResponse
  status: 200
}

export type postApiBookmarksIdFavoriteResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiBookmarksIdFavoriteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postApiBookmarksIdFavoriteResponse409 = {
  data: ErrorResponse
  status: 409
}

export type postApiBookmarksIdFavoriteResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type postApiBookmarksIdFavoriteResponseSuccess = (postApiBookmarksIdFavoriteResponse200) & {
  headers: Headers;
};
export type postApiBookmarksIdFavoriteResponseError = (postApiBookmarksIdFavoriteResponse400 | postApiBookmarksIdFavoriteResponse404 | postApiBookmarksIdFavoriteResponse409 | postApiBookmarksIdFavoriteResponse500) & {
  headers: Headers;
};

export type postApiBookmarksIdFavoriteResponse = (postApiBookmarksIdFavoriteResponseSuccess | postApiBookmarksIdFavoriteResponseError)

export const getPostApiBookmarksIdFavoriteUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/favorite`
}

export const postApiBookmarksIdFavorite = async (id: number, options?: RequestInit): Promise<postApiBookmarksIdFavoriteResponse> => {
  
  const res = await fetch(getPostApiBookmarksIdFavoriteUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiBookmarksIdFavoriteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiBookmarksIdFavoriteResponse
}



/**
 * @summary ブックマークへラベルを付与
 */
export type putApiBookmarksIdLabelResponse200 = {
  data: AssignLabelResponse
  status: 200
}

export type putApiBookmarksIdLabelResponse400 = {
  data: ErrorResponse
  status: 400
}

export type putApiBookmarksIdLabelResponse404 = {
  data: ErrorResponse
  status: 404
}

export type putApiBookmarksIdLabelResponse409 = {
  data: ErrorResponse
  status: 409
}

export type putApiBookmarksIdLabelResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type putApiBookmarksIdLabelResponseSuccess = (putApiBookmarksIdLabelResponse200) & {
  headers: Headers;
};
export type putApiBookmarksIdLabelResponseError = (putApiBookmarksIdLabelResponse400 | putApiBookmarksIdLabelResponse404 | putApiBookmarksIdLabelResponse409 | putApiBookmarksIdLabelResponse500) & {
  headers: Headers;
};

export type putApiBookmarksIdLabelResponse = (putApiBookmarksIdLabelResponseSuccess | putApiBookmarksIdLabelResponseError)

export const getPutApiBookmarksIdLabelUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/label`
}

export const putApiBookmarksIdLabel = async (id: number,
    assignLabelRequest: AssignLabelRequest, options?: RequestInit): Promise<putApiBookmarksIdLabelResponse> => {
  
  const res = await fetch(getPutApiBookmarksIdLabelUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignLabelRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiBookmarksIdLabelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiBookmarksIdLabelResponse
}



/**
 * @summary ブックマークを既読にする
 */
export type patchApiBookmarksIdReadResponse200 = {
  data: SuccessResponse
  status: 200
}

export type patchApiBookmarksIdReadResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchApiBookmarksIdReadResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchApiBookmarksIdReadResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type patchApiBookmarksIdReadResponseSuccess = (patchApiBookmarksIdReadResponse200) & {
  headers: Headers;
};
export type patchApiBookmarksIdReadResponseError = (patchApiBookmarksIdReadResponse400 | patchApiBookmarksIdReadResponse404 | patchApiBookmarksIdReadResponse500) & {
  headers: Headers;
};

export type patchApiBookmarksIdReadResponse = (patchApiBookmarksIdReadResponseSuccess | patchApiBookmarksIdReadResponseError)

export const getPatchApiBookmarksIdReadUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/read`
}

export const patchApiBookmarksIdRead = async (id: number, options?: RequestInit): Promise<patchApiBookmarksIdReadResponse> => {
  
  const res = await fetch(getPatchApiBookmarksIdReadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiBookmarksIdReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiBookmarksIdReadResponse
}



/**
 * @summary ブックマークを未読に戻す
 */
export type patchApiBookmarksIdUnreadResponse200 = {
  data: SuccessResponse
  status: 200
}

export type patchApiBookmarksIdUnreadResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchApiBookmarksIdUnreadResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchApiBookmarksIdUnreadResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type patchApiBookmarksIdUnreadResponseSuccess = (patchApiBookmarksIdUnreadResponse200) & {
  headers: Headers;
};
export type patchApiBookmarksIdUnreadResponseError = (patchApiBookmarksIdUnreadResponse400 | patchApiBookmarksIdUnreadResponse404 | patchApiBookmarksIdUnreadResponse500) & {
  headers: Headers;
};

export type patchApiBookmarksIdUnreadResponse = (patchApiBookmarksIdUnreadResponseSuccess | patchApiBookmarksIdUnreadResponseError)

export const getPatchApiBookmarksIdUnreadUrl = (id: number,) => {


  

  return `/api/bookmarks/${id}/unread`
}

export const patchApiBookmarksIdUnread = async (id: number, options?: RequestInit): Promise<patchApiBookmarksIdUnreadResponse> => {
  
  const res = await fetch(getPatchApiBookmarksIdUnreadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiBookmarksIdUnreadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiBookmarksIdUnreadResponse
}



/**
 * @summary ラベル一覧
 */
export type getApiLabelsResponse200 = {
  data: LabelsResponse
  status: 200
}

export type getApiLabelsResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type getApiLabelsResponseSuccess = (getApiLabelsResponse200) & {
  headers: Headers;
};
export type getApiLabelsResponseError = (getApiLabelsResponse500) & {
  headers: Headers;
};

export type getApiLabelsResponse = (getApiLabelsResponseSuccess | getApiLabelsResponseError)

export const getGetApiLabelsUrl = () => {


  

  return `/api/labels`
}

export const getApiLabels = async ( options?: RequestInit): Promise<getApiLabelsResponse> => {
  
  const res = await fetch(getGetApiLabelsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiLabelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiLabelsResponse
}



/**
 * @summary ラベル作成
 */
export type postApiLabelsResponse201 = {
  data: LabelResponse
  status: 201
}

export type postApiLabelsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postApiLabelsResponse409 = {
  data: ErrorResponse
  status: 409
}

export type postApiLabelsResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type postApiLabelsResponseSuccess = (postApiLabelsResponse201) & {
  headers: Headers;
};
export type postApiLabelsResponseError = (postApiLabelsResponse400 | postApiLabelsResponse409 | postApiLabelsResponse500) & {
  headers: Headers;
};

export type postApiLabelsResponse = (postApiLabelsResponseSuccess | postApiLabelsResponseError)

export const getPostApiLabelsUrl = () => {


  

  return `/api/labels`
}

export const postApiLabels = async (createLabelRequest: CreateLabelRequest, options?: RequestInit): Promise<postApiLabelsResponse> => {
  
  const res = await fetch(getPostApiLabelsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLabelRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiLabelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiLabelsResponse
}



/**
 * @summary 未使用ラベルの一括削除
 */
export type deleteApiLabelsCleanupResponse200 = {
  data: LabelCleanupResponse
  status: 200
}

export type deleteApiLabelsCleanupResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deleteApiLabelsCleanupResponseSuccess = (deleteApiLabelsCleanupResponse200) & {
  headers: Headers;
};
export type deleteApiLabelsCleanupResponseError = (deleteApiLabelsCleanupResponse500) & {
  headers: Headers;
};

export type deleteApiLabelsCleanupResponse = (deleteApiLabelsCleanupResponseSuccess | deleteApiLabelsCleanupResponseError)

export const getDeleteApiLabelsCleanupUrl = () => {


  

  return `/api/labels/cleanup`
}

export const deleteApiLabelsCleanup = async ( options?: RequestInit): Promise<deleteApiLabelsCleanupResponse> => {
  
  const res = await fetch(getDeleteApiLabelsCleanupUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiLabelsCleanupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiLabelsCleanupResponse
}



/**
 * @summary ラベル削除
 */
export type deleteApiLabelsIdResponse200 = {
  data: MessageResponse
  status: 200
}

export type deleteApiLabelsIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type deleteApiLabelsIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteApiLabelsIdResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type deleteApiLabelsIdResponseSuccess = (deleteApiLabelsIdResponse200) & {
  headers: Headers;
};
export type deleteApiLabelsIdResponseError = (deleteApiLabelsIdResponse400 | deleteApiLabelsIdResponse404 | deleteApiLabelsIdResponse500) & {
  headers: Headers;
};

export type deleteApiLabelsIdResponse = (deleteApiLabelsIdResponseSuccess | deleteApiLabelsIdResponseError)

export const getDeleteApiLabelsIdUrl = (id: number,) => {


  

  return `/api/labels/${id}`
}

export const deleteApiLabelsId = async (id: number, options?: RequestInit): Promise<deleteApiLabelsIdResponse> => {
  
  const res = await fetch(getDeleteApiLabelsIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiLabelsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiLabelsIdResponse
}



/**
 * @summary ラベル説明文の更新
 */
export type patchApiLabelsIdResponse200 = {
  data: LabelResponse
  status: 200
}

export type patchApiLabelsIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchApiLabelsIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchApiLabelsIdResponse500 = {
  data: ErrorResponse
  status: 500
}
    
export type patchApiLabelsIdResponseSuccess = (patchApiLabelsIdResponse200) & {
  headers: Headers;
};
export type patchApiLabelsIdResponseError = (patchApiLabelsIdResponse400 | patchApiLabelsIdResponse404 | patchApiLabelsIdResponse500) & {
  headers: Headers;
};

export type patchApiLabelsIdResponse = (patchApiLabelsIdResponseSuccess | patchApiLabelsIdResponseError)

export const getPatchApiLabelsIdUrl = (id: number,) => {


  

  return `/api/labels/${id}`
}

export const patchApiLabelsId = async (id: number,
    updateLabelRequest: UpdateLabelRequest, options?: RequestInit): Promise<patchApiLabelsIdResponse> => {
  
  const res = await fetch(getPatchApiLabelsIdUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLabelRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchApiLabelsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiLabelsIdResponse
}
