/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */

export interface Bookmark {
  /** ISO 8601 形式の日時 */
  createdAt: string;
  id: number;
  isRead: boolean;
  title?: string | null;
  /** ISO 8601 形式の日時 */
  updatedAt: string;
  url: string;
}
