/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */

export type GetApiBookmarksParams = {
/**
 * 取得件数の上限（1-100）。未指定時は全件取得
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
