/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */
import type { LabelWithCount } from './labelWithCount';

export type LabelsResponseAllOf = {
  labels: LabelWithCount[];
};
