/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */
import type { BookmarkWithFavorite } from './bookmarkWithFavorite';
import type { SuccessResponse } from './successResponse';

export type BookmarkListResponse = SuccessResponse & {
  bookmarks: BookmarkWithFavorite[];
  todayReadCount?: number;
  totalUnread?: number;
};
