/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */

export * from './assignLabelRequest';
export * from './assignLabelResponse';
export * from './assignLabelResponseAllOf';
export * from './batchLabelRequest';
export * from './batchLabelResponse';
export * from './batchLabelResponseAllOf';
export * from './batchLabelResponseAllOfErrorsItem';
export * from './bookmark';
export * from './bookmarkListResponse';
export * from './bookmarkListResponseAllOf';
export * from './bookmarkWithLabel';
export * from './bookmarkWithLabelLabel';
export * from './bulkBookmarksRequest';
export * from './bulkBookmarksRequestBookmarksItem';
export * from './createLabelRequest';
export * from './errorResponse';
export * from './favoriteBookmarksResponse';
export * from './favoriteBookmarksResponseAllOf';
export * from './getApiBookmarksParams';
export * from './label';
export * from './labelCleanupResponse';
export * from './labelCleanupResponseAllOf';
export * from './labelResponse';
export * from './labelResponseAllOf';
export * from './labelWithCount';
export * from './labelWithCountAllOf';
export * from './labelsResponse';
export * from './labelsResponseAllOf';
export * from './messageResponse';
export * from './messageResponseAllOf';
export * from './recentBookmarksResponse';
export * from './recentBookmarksResponseAllOf';
export * from './recentBookmarksResponseAllOfBookmarks';
export * from './successResponse';
export * from './unlabeledBookmarksResponse';
export * from './unlabeledBookmarksResponseAllOf';
export * from './unratedBookmarksResponse';
export * from './unratedBookmarksResponseAllOf';
export * from './updateLabelRequest';