/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */

export * from './bookmark';
export * from './bookmarkListResponse';
export * from './bookmarkWithFavorite';
export * from './bulkBookmarksRequest';
export * from './bulkBookmarksRequestBookmarksItem';
export * from './errorResponse';
export * from './favoriteBookmarksResponse';
export * from './messageResponse';
export * from './recentBookmarksResponse';
export * from './successResponse';