/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Yomimono API
 * ブックマーク管理を行う Yomimono API の OpenAPI 定義。
このファイルは src/openapi/spec.ts を唯一のソースとして生成されます。
 * OpenAPI spec version: 0.1.0
 */

export interface SeedOptions {
  /**
   * @minimum 1
   * @maximum 100
   */
  bookmarkCount?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  favoriteRatio?: number;
  forceRun?: boolean;
  /**
   * @minimum 1
   * @maximum 20
   */
  labelCount?: number;
}
