# SwiftLint 設定 - yomimono macOS アプリ
# Swift 6 + SwiftUI 向けルール設定

# 対象ディレクトリ
included:
  - Sources

# 除外パス
excluded:
  - build
  - .build

# 有効にする opt-in ルール
opt_in_rules:
  - array_init
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# 無効化するルール
disabled_rules:
  # SwiftUI のビュー定義では body が長くなりがち
  - function_body_length
  # SwiftUI の View は type_body_length が長くなる場合がある
  - type_body_length

# ルール設定
line_length:
  warning: 130
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok

file_length:
  warning: 400
  error: 600

type_name:
  min_length:
    warning: 3
    error: 2

cyclomatic_complexity:
  warning: 15
  error: 25
