name: yomimono
options:
  bundleIdPrefix: com.yomimono
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"

packages:
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: 9.0.0

targets:
  yomimono:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yomimono.macos
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Sources/yomimono.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
    dependencies:
      - package: FeedKit
    preBuildScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        script: |
          cd "${SRCROOT}"
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed. Install via Homebrew: brew install swiftlint"
          fi
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: yomimono
        CFBundleDisplayName: yomimono
        NSHumanReadableCopyright: ""
        LSMinimumSystemVersion: "13.0"

  yomimonoTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: yomimono
    settings:
      base:
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        GENERATE_INFOPLIST_FILE: "YES"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
