name: CI (Self-hosted Runner)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# 同一ブランチでの並列実行を制限
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  CI: true

jobs:
  # 変更されたパスを検出
  detect-changes:
    name: Detect Changes
    runs-on: self-hosted
    outputs:
      api: ${{ steps.filter.outputs.api }}
      frontend: ${{ steps.filter.outputs.frontend }}
      extension: ${{ steps.filter.outputs.extension }}
      mcp: ${{ steps.filter.outputs.mcp }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Detect changed paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          api:
            - 'api/**'
            - '.github/workflows/ci-self-hosted.yml'
          frontend:
            - 'frontend/**'
            - '.github/workflows/ci-self-hosted.yml'
          extension:
            - 'extension/**'
            - '.github/workflows/ci-self-hosted.yml'
          mcp:
            - 'mcp/**'
            - '.github/workflows/ci-self-hosted.yml'
  # API プロジェクトのテスト
  api-tests:
    name: API Tests
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: self-hosted
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: api-coverage
        path: ./api/coverage/
        retention-days: 7

  # フロントエンド プロジェクトのテスト
  frontend-tests:
    name: Frontend Tests
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: self-hosted
    timeout-minutes: 15

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm ci
        
        # npm依存関係バグの回避策
        echo "Applying workaround for native dependencies..."
        rm -rf node_modules/.rollup_cache node_modules/.vite
        npm install @rollup/rollup-linux-x64-gnu lightningcss-linux-x64-gnu --no-save

    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm run test:run

    - name: Upload test coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: ./frontend/coverage/
        retention-days: 7


  # Chrome拡張機能のテスト
  extension-tests:
    name: Extension Tests
    needs: detect-changes
    if: needs.detect-changes.outputs.extension == 'true'
    runs-on: self-hosted
    timeout-minutes: 5

    defaults:
      run:
        working-directory: ./extension

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Validate manifest
      run: |
        if [ -f manifest.json ]; then
          echo "✅ manifest.json exists"
          # JSON形式チェック
          cat manifest.json | jq . > /dev/null || (echo "❌ Invalid JSON in manifest.json" && exit 1)
          echo "✅ manifest.json is valid JSON"
        else
          echo "❌ manifest.json not found" && exit 1
        fi

  # MCP プロジェクトのテスト
  mcp-tests:
    name: MCP Tests
    needs: detect-changes
    if: needs.detect-changes.outputs.mcp == 'true'
    runs-on: self-hosted
    timeout-minutes: 8

    defaults:
      run:
        working-directory: ./mcp

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npm run typecheck

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build

    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mcp-coverage
        path: ./mcp/coverage/
        retention-days: 7


