name: MCP Lint

on:
  pull_request:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-lint.yml'

jobs:
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./mcp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: mcp/package-lock.json

      - name: Setup npm path
        run: |
          echo "Current PATH: $PATH"
          # Add common Node.js paths to PATH  
          export PATH="/home/runner-user/yomimono-runnner/_work/_tool/node/20.19.2/x64/bin:$PATH"
          echo "Updated PATH: $PATH"
          echo "PATH=/home/runner-user/yomimono-runnner/_work/_tool/node/20.19.2/x64/bin:$PATH" >> $GITHUB_ENV
          # Verify installations
          which node && node --version
          which npm && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        
      - name: Type check
        run: npm run typecheck