name: MCP Tests

on:
  pull_request:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-test.yml'
    types: [opened, synchronize, reopened]

jobs:
  mcp-tests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./mcp

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mcp/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run test:coverage
      
      - name: Extract coverage percentage
        run: |
          COVERAGE=$(jq -r '.total.lines.pct' coverage/coverage-summary.json)
          echo "Coverage: ${COVERAGE}%"
          echo "COVERAGE_PCT=${COVERAGE}" >> $GITHUB_ENV
      
      - name: Comment PR with coverage
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ github.token }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"📊 **MCP Test Coverage**: ${COVERAGE_PCT}%\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"