name: MCP Lint

on:
  pull_request:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-lint.yml'

jobs:
  lint:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./mcp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: mcp/package-lock.json

      - name: Verify npm installation
        run: |
          which node || echo "Node not found"
          which npm || echo "npm not found"
          npm --version || echo "npm version failed"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        
      - name: Type check
        run: npm run typecheck